"""empty message

Revision ID: 5b59af14d17b
Revises: d950bc80a9ff
Create Date: 2022-04-26 15:46:14.007294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b59af14d17b'
down_revision = 'd950bc80a9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_name', table_name='tasks')
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.create_index('ix_tasks_name', 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###
